package com.hackstreak.learning_platform.config;

import com.hackstreak.learning_platform.entity.*;
import com.hackstreak.learning_platform.repository.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.*;

@Configuration
public class DataInitializer {

    @Bean
    public CommandLineRunner loadData(UserRepository userRepository,
                                      SubjectRepository subjectRepository,
                                      ChapterRepository chapterRepository,
                                      ConceptRepository conceptRepository,
                                      QuestionRepository questionRepository,
                                      LearningResourceRepository learningResourceRepository) {
        return args -> {
            if (userRepository.count() > 0) return;

            User student = new User();
            student.setName("Demo Student");
            student.setEmail("student@example.com");
            student.setPassword("hackathon123");
            userRepository.save(student);

            Map<String, Concept> conceptMap = new HashMap<>();
            Subject s_DatabaseManagement = createSubject("Database Management", "Database Management Systems");
            subjectRepository.save(s_DatabaseManagement);
            Chapter ch_DBMSFundamentals = createChapter("DBMS Fundamentals", s_DatabaseManagement);
            chapterRepository.save(ch_DBMSFundamentals);
            Concept con_DBMSvsFileSystem = createConcept("DBMS vs File System", ch_DBMSFundamentals);
            conceptMap.put("DBMS vs File System", con_DBMSvsFileSystem);
            Chapter ch_RelationalModel = createChapter("Relational Model", s_DatabaseManagement);
            chapterRepository.save(ch_RelationalModel);
            Concept con_EntitiesandAttributes = createConcept("Entities and Attributes", ch_RelationalModel);
            conceptMap.put("Entities and Attributes", con_EntitiesandAttributes);
            Concept con_PrimaryKey = createConcept("Primary Key", ch_RelationalModel);
            conceptMap.put("Primary Key", con_PrimaryKey);
            Concept con_ForeignKey = createConcept("Foreign Key", ch_RelationalModel);
            conceptMap.put("Foreign Key", con_ForeignKey);
            Chapter ch_SQL = createChapter("SQL", s_DatabaseManagement);
            chapterRepository.save(ch_SQL);
            Concept con_CREATETABLE = createConcept("CREATE TABLE", ch_SQL);
            conceptMap.put("CREATE TABLE", con_CREATETABLE);
            Concept con_SELECT = createConcept("SELECT", ch_SQL);
            conceptMap.put("SELECT", con_SELECT);
            Concept con_JOIN = createConcept("JOIN", ch_SQL);
            conceptMap.put("JOIN", con_JOIN);
            Chapter ch_Normalization = createChapter("Normalization", s_DatabaseManagement);
            chapterRepository.save(ch_Normalization);
            Concept con_FunctionalDependency = createConcept("Functional Dependency", ch_Normalization);
            conceptMap.put("Functional Dependency", con_FunctionalDependency);
            Concept con_1NF2NF3NF = createConcept("1NF 2NF 3NF", ch_Normalization);
            conceptMap.put("1NF 2NF 3NF", con_1NF2NF3NF);
            Subject s_DataStructures = createSubject("Data Structures", "Data Structures and Algorithms");
            subjectRepository.save(s_DataStructures);
            Chapter ch_Arrays = createChapter("Arrays", s_DataStructures);
            chapterRepository.save(ch_Arrays);
            Concept con_Arrayoperations = createConcept("Array operations", ch_Arrays);
            conceptMap.put("Array operations", con_Arrayoperations);
            Concept con_BinarySearch = createConcept("Binary Search", ch_Arrays);
            conceptMap.put("Binary Search", con_BinarySearch);
            Chapter ch_LinkedLists = createChapter("Linked Lists", s_DataStructures);
            chapterRepository.save(ch_LinkedLists);
            Concept con_SinglyLinkedList = createConcept("Singly Linked List", ch_LinkedLists);
            conceptMap.put("Singly Linked List", con_SinglyLinkedList);
            Chapter ch_Trees = createChapter("Trees", s_DataStructures);
            chapterRepository.save(ch_Trees);
            Concept con_BinaryTree = createConcept("Binary Tree", ch_Trees);
            conceptMap.put("Binary Tree", con_BinaryTree);
            Concept con_BST = createConcept("BST", ch_Trees);
            conceptMap.put("BST", con_BST);
            Concept con_TreeTraversals = createConcept("Tree Traversals", ch_Trees);
            conceptMap.put("Tree Traversals", con_TreeTraversals);
            Chapter ch_Sorting = createChapter("Sorting", s_DataStructures);
            chapterRepository.save(ch_Sorting);
            Concept con_MergeSort = createConcept("Merge Sort", ch_Sorting);
            conceptMap.put("Merge Sort", con_MergeSort);
            Subject s_Java = createSubject("Java", "Java Programming Language");
            subjectRepository.save(s_Java);
            Chapter ch_JavaFundamentals = createChapter("Java Fundamentals", s_Java);
            chapterRepository.save(ch_JavaFundamentals);
            Concept con_VariablesandDataTypes = createConcept("Variables and Data Types", ch_JavaFundamentals);
            conceptMap.put("Variables and Data Types", con_VariablesandDataTypes);
            Chapter ch_OOP = createChapter("OOP", s_Java);
            chapterRepository.save(ch_OOP);
            Concept con_ClassesandObjects = createConcept("Classes and Objects", ch_OOP);
            conceptMap.put("Classes and Objects", con_ClassesandObjects);
            Concept con_Inheritance = createConcept("Inheritance", ch_OOP);
            conceptMap.put("Inheritance", con_Inheritance);
            Concept con_Polymorphism = createConcept("Polymorphism", ch_OOP);
            conceptMap.put("Polymorphism", con_Polymorphism);
            Chapter ch_Collections = createChapter("Collections", s_Java);
            chapterRepository.save(ch_Collections);
            Concept con_ArrayList = createConcept("ArrayList", ch_Collections);
            conceptMap.put("ArrayList", con_ArrayList);
            Concept con_HashMap = createConcept("HashMap", ch_Collections);
            conceptMap.put("HashMap", con_HashMap);
            Subject s_Python = createSubject("Python", "Python Programming");
            subjectRepository.save(s_Python);
            Chapter ch_PythonFundamentals = createChapter("Python Fundamentals", s_Python);
            chapterRepository.save(ch_PythonFundamentals);
            Concept con_Variables = createConcept("Variables", ch_PythonFundamentals);
            conceptMap.put("Variables", con_Variables);
            Chapter ch_ControlFlow = createChapter("Control Flow", s_Python);
            chapterRepository.save(ch_ControlFlow);
            Concept con_forwhileloops = createConcept("for while loops", ch_ControlFlow);
            conceptMap.put("for while loops", con_forwhileloops);
            Chapter ch_DataStructures = createChapter("Data Structures", s_Python);
            chapterRepository.save(ch_DataStructures);
            Concept con_PythonLists = createConcept("Python Lists", ch_DataStructures);
            conceptMap.put("Python Lists", con_PythonLists);
            Concept con_ListComprehension = createConcept("List Comprehension", ch_DataStructures);
            conceptMap.put("List Comprehension", con_ListComprehension);
            Subject s_Reactjs = createSubject("React.js", "React Frontend Library");
            subjectRepository.save(s_Reactjs);
            Chapter ch_ReactFundamentals = createChapter("React Fundamentals", s_Reactjs);
            chapterRepository.save(ch_ReactFundamentals);
            Concept con_ReactComponents = createConcept("React Components", ch_ReactFundamentals);
            conceptMap.put("React Components", con_ReactComponents);
            Concept con_JSX = createConcept("JSX", ch_ReactFundamentals);
            conceptMap.put("JSX", con_JSX);
            Chapter ch_PropsandState = createChapter("Props and State", s_Reactjs);
            chapterRepository.save(ch_PropsandState);
            Concept con_State = createConcept("State", ch_PropsandState);
            conceptMap.put("State", con_State);
            Concept con_useState = createConcept("useState", ch_PropsandState);
            conceptMap.put("useState", con_useState);
            Chapter ch_Hooks = createChapter("Hooks", s_Reactjs);
            chapterRepository.save(ch_Hooks);
            Concept con_useEffect = createConcept("useEffect", ch_Hooks);
            conceptMap.put("useEffect", con_useEffect);
            Concept con_APIIntegration = createConcept("API Integration", ch_Hooks);
            conceptMap.put("API Integration", con_APIIntegration);
            Subject s_AutomataTheory = createSubject("Automata Theory", "Theory of Computation");
            subjectRepository.save(s_AutomataTheory);
            Chapter ch_FiniteAutomata = createChapter("Finite Automata", s_AutomataTheory);
            chapterRepository.save(ch_FiniteAutomata);
            Concept con_AlphabetandStrings = createConcept("Alphabet and Strings", ch_FiniteAutomata);
            conceptMap.put("Alphabet and Strings", con_AlphabetandStrings);
            Concept con_FiniteAutomatabasics = createConcept("Finite Automata basics", ch_FiniteAutomata);
            conceptMap.put("Finite Automata basics", con_FiniteAutomatabasics);
            Concept con_DFA = createConcept("DFA", ch_FiniteAutomata);
            conceptMap.put("DFA", con_DFA);
            Chapter ch_ContextFreeGrammars = createChapter("Context-Free Grammars", s_AutomataTheory);
            chapterRepository.save(ch_ContextFreeGrammars);
            Concept con_CFG = createConcept("CFG", ch_ContextFreeGrammars);
            conceptMap.put("CFG", con_CFG);
            Chapter ch_PushdownAutomata = createChapter("Pushdown Automata", s_AutomataTheory);
            chapterRepository.save(ch_PushdownAutomata);
            Concept con_PDA = createConcept("PDA", ch_PushdownAutomata);
            conceptMap.put("PDA", con_PDA);

            // Save all concepts first
            for(Concept c : conceptMap.values()) {
                conceptRepository.save(c);
            }
            // Set dependencies
            conceptMap.get("Primary Key").setPrerequisites(Arrays.asList(conceptMap.get("Entities and Attributes")));
            conceptMap.get("Foreign Key").setPrerequisites(Arrays.asList(conceptMap.get("Primary Key")));
            conceptMap.get("CREATE TABLE").setPrerequisites(Arrays.asList(conceptMap.get("Entities and Attributes")));
            conceptMap.get("SELECT").setPrerequisites(Arrays.asList(conceptMap.get("CREATE TABLE")));
            conceptMap.get("JOIN").setPrerequisites(Arrays.asList(conceptMap.get("SELECT"), conceptMap.get("Foreign Key")));
            conceptMap.get("Functional Dependency").setPrerequisites(Arrays.asList(conceptMap.get("Primary Key")));
            conceptMap.get("1NF 2NF 3NF").setPrerequisites(Arrays.asList(conceptMap.get("Functional Dependency")));
            conceptMap.get("Binary Search").setPrerequisites(Arrays.asList(conceptMap.get("Array operations")));
            conceptMap.get("Binary Tree").setPrerequisites(Arrays.asList(conceptMap.get("Singly Linked List")));
            conceptMap.get("BST").setPrerequisites(Arrays.asList(conceptMap.get("Binary Tree"), conceptMap.get("Binary Search")));
            conceptMap.get("Tree Traversals").setPrerequisites(Arrays.asList(conceptMap.get("Binary Tree")));
            conceptMap.get("Merge Sort").setPrerequisites(Arrays.asList(conceptMap.get("Array operations")));
            conceptMap.get("Classes and Objects").setPrerequisites(Arrays.asList(conceptMap.get("Variables and Data Types")));
            conceptMap.get("Inheritance").setPrerequisites(Arrays.asList(conceptMap.get("Classes and Objects")));
            conceptMap.get("Polymorphism").setPrerequisites(Arrays.asList(conceptMap.get("Inheritance")));
            conceptMap.get("ArrayList").setPrerequisites(Arrays.asList(conceptMap.get("Classes and Objects")));
            conceptMap.get("HashMap").setPrerequisites(Arrays.asList(conceptMap.get("Classes and Objects")));
            conceptMap.get("for while loops").setPrerequisites(Arrays.asList(conceptMap.get("Variables")));
            conceptMap.get("Python Lists").setPrerequisites(Arrays.asList(conceptMap.get("Variables")));
            conceptMap.get("List Comprehension").setPrerequisites(Arrays.asList(conceptMap.get("Python Lists"), conceptMap.get("for while loops")));
            conceptMap.get("JSX").setPrerequisites(Arrays.asList(conceptMap.get("React Components")));
            conceptMap.get("State").setPrerequisites(Arrays.asList(conceptMap.get("React Components")));
            conceptMap.get("useState").setPrerequisites(Arrays.asList(conceptMap.get("State")));
            conceptMap.get("useEffect").setPrerequisites(Arrays.asList(conceptMap.get("useState")));
            conceptMap.get("API Integration").setPrerequisites(Arrays.asList(conceptMap.get("useEffect")));
            conceptMap.get("Finite Automata basics").setPrerequisites(Arrays.asList(conceptMap.get("Alphabet and Strings")));
            conceptMap.get("DFA").setPrerequisites(Arrays.asList(conceptMap.get("Finite Automata basics")));
            conceptMap.get("CFG").setPrerequisites(Arrays.asList(conceptMap.get("Alphabet and Strings")));
            conceptMap.get("PDA").setPrerequisites(Arrays.asList(conceptMap.get("CFG"), conceptMap.get("Finite Automata basics")));

            // Resave concepts with dependencies
            for(Concept c : conceptMap.values()) {
                conceptRepository.save(c);
            }

            // Generate questions and resources
            for (Map.Entry<String, Concept> entry : conceptMap.entrySet()) {
                createQuestionsForConcept(questionRepository, entry.getValue(), entry.getKey(), 10);
            }
            learningResourceRepository.save(createResource(conceptMap.get("DBMS vs File System"), "Intro to DBMS", "DBMS provides abstraction, security, and crash recovery compared to a file system.", "Use DBMS for structured data.", "Understand data abstraction layers.", "The concept of DBMS vs File System is fundamental to mastering DBMS Fundamentals. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of DBMS Fundamentals\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for DBMS vs File System\nUse DBMS for structured data.\n// Usage depends on context", "In real-world applications, DBMS vs File System is used heavily by companies like Google and Meta to optimize their DBMS Fundamentals pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply DBMS vs File System principles.\nStep 3: Use DBMS for structured data.\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the DBMS vs File System implementation.", "Frequently Asked:\n- Define DBMS vs File System.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating DBMS vs File System."));
            learningResourceRepository.save(createResource(conceptMap.get("Entities and Attributes"), "Entities & Attributes", "An entity is a real-world object; attributes are its properties.", "Student(RollNo, Name)", "Identify the entity first.", "The concept of Entities and Attributes is fundamental to mastering Relational Model. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Relational Model\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Entities and Attributes\nStudent(RollNo, Name)\n// Usage depends on context", "In real-world applications, Entities and Attributes is used heavily by companies like Google and Meta to optimize their Relational Model pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Entities and Attributes principles.\nStep 3: Student(RollNo, Name)\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Entities and Attributes implementation.", "Frequently Asked:\n- Define Entities and Attributes.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Entities and Attributes."));
            learningResourceRepository.save(createResource(conceptMap.get("Primary Key"), "Primary Keys", "A column or set of columns that uniquely identifies a row.", "PRIMARY KEY (id)", "It cannot be NULL.", "The concept of Primary Key is fundamental to mastering Relational Model. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Relational Model\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Primary Key\nPRIMARY KEY (id)\n// Usage depends on context", "In real-world applications, Primary Key is used heavily by companies like Google and Meta to optimize their Relational Model pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Primary Key principles.\nStep 3: PRIMARY KEY (id)\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Primary Key implementation.", "Frequently Asked:\n- Define Primary Key.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Primary Key."));
            learningResourceRepository.save(createResource(conceptMap.get("Foreign Key"), "Foreign Keys", "A key that links two tables together.", "FOREIGN KEY (dept_id) REFERENCES Dept(id)", "Maintains referential integrity.", "The concept of Foreign Key is fundamental to mastering Relational Model. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Relational Model\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Foreign Key\nFOREIGN KEY (dept_id) REFERENCES Dept(id)\n// Usage depends on context", "In real-world applications, Foreign Key is used heavily by companies like Google and Meta to optimize their Relational Model pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Foreign Key principles.\nStep 3: FOREIGN KEY (dept_id) REFERENCES Dept(id)\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Foreign Key implementation.", "Frequently Asked:\n- Define Foreign Key.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Foreign Key."));
            learningResourceRepository.save(createResource(conceptMap.get("CREATE TABLE"), "CREATE TABLE", "Defines a new table schema.", "CREATE TABLE users (id INT);", "Define data types.", "The concept of CREATE TABLE is fundamental to mastering SQL. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of SQL\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for CREATE TABLE\nCREATE TABLE users (id INT);\n// Usage depends on context", "In real-world applications, CREATE TABLE is used heavily by companies like Google and Meta to optimize their SQL pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply CREATE TABLE principles.\nStep 3: CREATE TABLE users (id INT);\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the CREATE TABLE implementation.", "Frequently Asked:\n- Define CREATE TABLE.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating CREATE TABLE."));
            learningResourceRepository.save(createResource(conceptMap.get("SELECT"), "SELECT Query", "Retrieves data from a table.", "SELECT * FROM users;", "Can filter with WHERE.", "The concept of SELECT is fundamental to mastering SQL. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of SQL\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for SELECT\nSELECT * FROM users;\n// Usage depends on context", "In real-world applications, SELECT is used heavily by companies like Google and Meta to optimize their SQL pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply SELECT principles.\nStep 3: SELECT * FROM users;\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the SELECT implementation.", "Frequently Asked:\n- Define SELECT.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating SELECT."));
            learningResourceRepository.save(createResource(conceptMap.get("JOIN"), "SQL JOIN", "Combines rows from two or more tables.", "SELECT * FROM A JOIN B ON A.id = B.a_id;", "Understand INNER vs OUTER join.", "The concept of JOIN is fundamental to mastering SQL. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of SQL\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for JOIN\nSELECT * FROM A JOIN B ON A.id = B.a_id;\n// Usage depends on context", "In real-world applications, JOIN is used heavily by companies like Google and Meta to optimize their SQL pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply JOIN principles.\nStep 3: SELECT * FROM A JOIN B ON A.id = B.a_id;\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the JOIN implementation.", "Frequently Asked:\n- Define JOIN.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating JOIN."));
            learningResourceRepository.save(createResource(conceptMap.get("Functional Dependency"), "Functional Dependency", "A relationship where one attribute uniquely determines another.", "X -> Y", "Crucial for normalization.", "The concept of Functional Dependency is fundamental to mastering Normalization. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Normalization\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Functional Dependency\nX -> Y\n// Usage depends on context", "In real-world applications, Functional Dependency is used heavily by companies like Google and Meta to optimize their Normalization pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Functional Dependency principles.\nStep 3: X -> Y\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Functional Dependency implementation.", "Frequently Asked:\n- Define Functional Dependency.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Functional Dependency."));
            learningResourceRepository.save(createResource(conceptMap.get("1NF 2NF 3NF"), "Normal Forms", "Rules to reduce data redundancy.", "3NF removes transitive dependencies.", "Go step-by-step from 1NF to 3NF.", "The concept of 1NF 2NF 3NF is fundamental to mastering Normalization. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Normalization\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for 1NF 2NF 3NF\n3NF removes transitive dependencies.\n// Usage depends on context", "In real-world applications, 1NF 2NF 3NF is used heavily by companies like Google and Meta to optimize their Normalization pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply 1NF 2NF 3NF principles.\nStep 3: 3NF removes transitive dependencies.\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the 1NF 2NF 3NF implementation.", "Frequently Asked:\n- Define 1NF 2NF 3NF.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating 1NF 2NF 3NF."));
            learningResourceRepository.save(createResource(conceptMap.get("Array operations"), "Arrays", "Contiguous memory locations for data.", "arr[0] = 5;", "O(1) access time.", "The concept of Array operations is fundamental to mastering Arrays. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Arrays\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Array operations\narr[0] = 5;\n// Usage depends on context", "In real-world applications, Array operations is used heavily by companies like Google and Meta to optimize their Arrays pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Array operations principles.\nStep 3: arr[0] = 5;\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Array operations implementation.", "Frequently Asked:\n- Define Array operations.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Array operations."));
            learningResourceRepository.save(createResource(conceptMap.get("Binary Search"), "Binary Search", "Search a sorted array by repeatedly dividing the search interval in half.", "mid = (low + high) / 2", "Array MUST be sorted.", "The concept of Binary Search is fundamental to mastering Arrays. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Arrays\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Binary Search\nmid = (low + high) / 2\n// Usage depends on context", "In real-world applications, Binary Search is used heavily by companies like Google and Meta to optimize their Arrays pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Binary Search principles.\nStep 3: mid = (low + high) / 2\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Binary Search implementation.", "Frequently Asked:\n- Define Binary Search.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Binary Search."));
            learningResourceRepository.save(createResource(conceptMap.get("Singly Linked List"), "Linked List", "Nodes containing data and a pointer to the next node.", "node.next = newNode", "O(N) access time.", "The concept of Singly Linked List is fundamental to mastering Linked Lists. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Linked Lists\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Singly Linked List\nnode.next = newNode\n// Usage depends on context", "In real-world applications, Singly Linked List is used heavily by companies like Google and Meta to optimize their Linked Lists pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Singly Linked List principles.\nStep 3: node.next = newNode\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Singly Linked List implementation.", "Frequently Asked:\n- Define Singly Linked List.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Singly Linked List."));
            learningResourceRepository.save(createResource(conceptMap.get("Binary Tree"), "Binary Tree", "Tree where each node has at most two children.", "node.left, node.right", "Understand height and depth.", "The concept of Binary Tree is fundamental to mastering Trees. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Trees\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Binary Tree\nnode.left, node.right\n// Usage depends on context", "In real-world applications, Binary Tree is used heavily by companies like Google and Meta to optimize their Trees pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Binary Tree principles.\nStep 3: node.left, node.right\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Binary Tree implementation.", "Frequently Asked:\n- Define Binary Tree.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Binary Tree."));
            learningResourceRepository.save(createResource(conceptMap.get("BST"), "Binary Search Tree", "Left child < parent < right child.", "if (val < root.val) goLeft();", "Inorder traversal gives sorted order.", "The concept of BST is fundamental to mastering Trees. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Trees\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for BST\nif (val < root.val) goLeft();\n// Usage depends on context", "In real-world applications, BST is used heavily by companies like Google and Meta to optimize their Trees pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply BST principles.\nStep 3: if (val < root.val) goLeft();\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the BST implementation.", "Frequently Asked:\n- Define BST.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating BST."));
            learningResourceRepository.save(createResource(conceptMap.get("Tree Traversals"), "Traversals", "Preorder, Inorder, Postorder.", "Inorder: Left, Root, Right", "Often uses recursion.", "The concept of Tree Traversals is fundamental to mastering Trees. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Trees\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Tree Traversals\nInorder: Left, Root, Right\n// Usage depends on context", "In real-world applications, Tree Traversals is used heavily by companies like Google and Meta to optimize their Trees pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Tree Traversals principles.\nStep 3: Inorder: Left, Root, Right\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Tree Traversals implementation.", "Frequently Asked:\n- Define Tree Traversals.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Tree Traversals."));
            learningResourceRepository.save(createResource(conceptMap.get("Merge Sort"), "Merge Sort", "Divide and conquer sorting algorithm.", "merge(left, right)", "Time complexity is always O(N log N).", "The concept of Merge Sort is fundamental to mastering Sorting. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Sorting\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Merge Sort\nmerge(left, right)\n// Usage depends on context", "In real-world applications, Merge Sort is used heavily by companies like Google and Meta to optimize their Sorting pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Merge Sort principles.\nStep 3: merge(left, right)\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Merge Sort implementation.", "Frequently Asked:\n- Define Merge Sort.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Merge Sort."));
            learningResourceRepository.save(createResource(conceptMap.get("Variables and Data Types"), "Java Variables", "Strongly typed variables.", "int count = 10;", "Primitives vs Objects.", "The concept of Variables and Data Types is fundamental to mastering Java Fundamentals. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Java Fundamentals\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Variables and Data Types\nint count = 10;\n// Usage depends on context", "In real-world applications, Variables and Data Types is used heavily by companies like Google and Meta to optimize their Java Fundamentals pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Variables and Data Types principles.\nStep 3: int count = 10;\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Variables and Data Types implementation.", "Frequently Asked:\n- Define Variables and Data Types.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Variables and Data Types."));
            learningResourceRepository.save(createResource(conceptMap.get("Classes and Objects"), "Classes and Objects", "Class is blueprint, object is instance.", "Car myCar = new Car();", "Use new keyword.", "The concept of Classes and Objects is fundamental to mastering OOP. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of OOP\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Classes and Objects\nCar myCar = new Car();\n// Usage depends on context", "In real-world applications, Classes and Objects is used heavily by companies like Google and Meta to optimize their OOP pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Classes and Objects principles.\nStep 3: Car myCar = new Car();\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Classes and Objects implementation.", "Frequently Asked:\n- Define Classes and Objects.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Classes and Objects."));
            learningResourceRepository.save(createResource(conceptMap.get("Inheritance"), "Inheritance", "Mechanism where one class acquires properties of another.", "class Dog extends Animal {}", "Java doesn't support multiple inheritance.", "The concept of Inheritance is fundamental to mastering OOP. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of OOP\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Inheritance\nclass Dog extends Animal {}\n// Usage depends on context", "In real-world applications, Inheritance is used heavily by companies like Google and Meta to optimize their OOP pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Inheritance principles.\nStep 3: class Dog extends Animal {}\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Inheritance implementation.", "Frequently Asked:\n- Define Inheritance.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Inheritance."));
            learningResourceRepository.save(createResource(conceptMap.get("Polymorphism"), "Polymorphism", "One interface, multiple methods.", "Animal a = new Dog(); a.makeSound();", "Method overriding is runtime polymorphism.", "The concept of Polymorphism is fundamental to mastering OOP. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of OOP\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Polymorphism\nAnimal a = new Dog(); a.makeSound();\n// Usage depends on context", "In real-world applications, Polymorphism is used heavily by companies like Google and Meta to optimize their OOP pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Polymorphism principles.\nStep 3: Animal a = new Dog(); a.makeSound();\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Polymorphism implementation.", "Frequently Asked:\n- Define Polymorphism.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Polymorphism."));
            learningResourceRepository.save(createResource(conceptMap.get("ArrayList"), "ArrayList", "Dynamic array implementation in Java.", "list.add('item');", "Uses wrapper classes like Integer.", "The concept of ArrayList is fundamental to mastering Collections. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Collections\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for ArrayList\nlist.add('item');\n// Usage depends on context", "In real-world applications, ArrayList is used heavily by companies like Google and Meta to optimize their Collections pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply ArrayList principles.\nStep 3: list.add('item');\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the ArrayList implementation.", "Frequently Asked:\n- Define ArrayList.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating ArrayList."));
            learningResourceRepository.save(createResource(conceptMap.get("HashMap"), "HashMap", "Key-value pair data structure.", "map.put('key', 'value');", "Keys must be unique.", "The concept of HashMap is fundamental to mastering Collections. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Collections\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for HashMap\nmap.put('key', 'value');\n// Usage depends on context", "In real-world applications, HashMap is used heavily by companies like Google and Meta to optimize their Collections pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply HashMap principles.\nStep 3: map.put('key', 'value');\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the HashMap implementation.", "Frequently Asked:\n- Define HashMap.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating HashMap."));
            learningResourceRepository.save(createResource(conceptMap.get("Variables"), "Python Variables", "Dynamically typed references.", "x = 5", "No type declaration.", "The concept of Variables is fundamental to mastering Python Fundamentals. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Python Fundamentals\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Variables\nx = 5\n// Usage depends on context", "In real-world applications, Variables is used heavily by companies like Google and Meta to optimize their Python Fundamentals pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Variables principles.\nStep 3: x = 5\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Variables implementation.", "Frequently Asked:\n- Define Variables.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Variables."));
            learningResourceRepository.save(createResource(conceptMap.get("for while loops"), "Loops", "Iterate over sequences.", "for i in range(5):", "Indentation matters.", "The concept of for while loops is fundamental to mastering Control Flow. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Control Flow\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for for while loops\nfor i in range(5):\n// Usage depends on context", "In real-world applications, for while loops is used heavily by companies like Google and Meta to optimize their Control Flow pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply for while loops principles.\nStep 3: for i in range(5):\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the for while loops implementation.", "Frequently Asked:\n- Define for while loops.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating for while loops."));
            learningResourceRepository.save(createResource(conceptMap.get("Python Lists"), "Lists", "Mutable sequence of elements.", "my_list = [1, 2, 3]", "Can hold mixed types.", "The concept of Python Lists is fundamental to mastering Data Structures. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Data Structures\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Python Lists\nmy_list = [1, 2, 3]\n// Usage depends on context", "In real-world applications, Python Lists is used heavily by companies like Google and Meta to optimize their Data Structures pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Python Lists principles.\nStep 3: my_list = [1, 2, 3]\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Python Lists implementation.", "Frequently Asked:\n- Define Python Lists.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Python Lists."));
            learningResourceRepository.save(createResource(conceptMap.get("List Comprehension"), "List Comprehension", "Concise way to create lists.", "[x*2 for x in range(5)]", "Great for filtering and mapping.", "The concept of List Comprehension is fundamental to mastering Data Structures. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Data Structures\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for List Comprehension\n[x*2 for x in range(5)]\n// Usage depends on context", "In real-world applications, List Comprehension is used heavily by companies like Google and Meta to optimize their Data Structures pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply List Comprehension principles.\nStep 3: [x*2 for x in range(5)]\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the List Comprehension implementation.", "Frequently Asked:\n- Define List Comprehension.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating List Comprehension."));
            learningResourceRepository.save(createResource(conceptMap.get("React Components"), "Components", "Reusable UI building blocks.", "function Button() { return <button/>; }", "Start names with a capital letter.", "The concept of React Components is fundamental to mastering React Fundamentals. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of React Fundamentals\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for React Components\nfunction Button() { return <button/>; }\n// Usage depends on context", "In real-world applications, React Components is used heavily by companies like Google and Meta to optimize their React Fundamentals pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply React Components principles.\nStep 3: function Button() { return <button/>; }\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the React Components implementation.", "Frequently Asked:\n- Define React Components.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating React Components."));
            learningResourceRepository.save(createResource(conceptMap.get("JSX"), "JSX", "Syntax extension for JS.", "<div className='box'></div>", "Use className instead of class.", "The concept of JSX is fundamental to mastering React Fundamentals. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of React Fundamentals\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for JSX\n<div className='box'></div>\n// Usage depends on context", "In real-world applications, JSX is used heavily by companies like Google and Meta to optimize their React Fundamentals pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply JSX principles.\nStep 3: <div className='box'></div>\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the JSX implementation.", "Frequently Asked:\n- Define JSX.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating JSX."));
            learningResourceRepository.save(createResource(conceptMap.get("State"), "React State", "Data that changes over time in a component.", "State belongs to the component.", "Do not mutate state directly.", "The concept of State is fundamental to mastering Props and State. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Props and State\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for State\nState belongs to the component.\n// Usage depends on context", "In real-world applications, State is used heavily by companies like Google and Meta to optimize their Props and State pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply State principles.\nStep 3: State belongs to the component.\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the State implementation.", "Frequently Asked:\n- Define State.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating State."));
            learningResourceRepository.save(createResource(conceptMap.get("useState"), "useState Hook", "Hook to add state to function components.", "const [count, setCount] = useState(0);", "Triggers re-render on update.", "The concept of useState is fundamental to mastering Props and State. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Props and State\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for useState\nconst [count, setCount] = useState(0);\n// Usage depends on context", "In real-world applications, useState is used heavily by companies like Google and Meta to optimize their Props and State pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply useState principles.\nStep 3: const [count, setCount] = useState(0);\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the useState implementation.", "Frequently Asked:\n- Define useState.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating useState."));
            learningResourceRepository.save(createResource(conceptMap.get("useEffect"), "useEffect Hook", "Perform side effects in function components.", "useEffect(() => { ... }, []);", "Empty dependency array runs once.", "The concept of useEffect is fundamental to mastering Hooks. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Hooks\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for useEffect\nuseEffect(() => { ... }, []);\n// Usage depends on context", "In real-world applications, useEffect is used heavily by companies like Google and Meta to optimize their Hooks pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply useEffect principles.\nStep 3: useEffect(() => { ... }, []);\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the useEffect implementation.", "Frequently Asked:\n- Define useEffect.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating useEffect."));
            learningResourceRepository.save(createResource(conceptMap.get("API Integration"), "API Calls", "Fetching data from a backend.", "fetch('/api/data').then(...)", "Do this inside useEffect.", "The concept of API Integration is fundamental to mastering Hooks. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Hooks\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for API Integration\nfetch('/api/data').then(...)\n// Usage depends on context", "In real-world applications, API Integration is used heavily by companies like Google and Meta to optimize their Hooks pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply API Integration principles.\nStep 3: fetch('/api/data').then(...)\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the API Integration implementation.", "Frequently Asked:\n- Define API Integration.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating API Integration."));
            learningResourceRepository.save(createResource(conceptMap.get("Alphabet and Strings"), "Alphabet and Strings", "An alphabet is a finite set of symbols.", "Σ = {0, 1}", "A string is a finite sequence of symbols.", "The concept of Alphabet and Strings is fundamental to mastering Finite Automata. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Finite Automata\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Alphabet and Strings\nΣ = {0, 1}\n// Usage depends on context", "In real-world applications, Alphabet and Strings is used heavily by companies like Google and Meta to optimize their Finite Automata pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Alphabet and Strings principles.\nStep 3: Σ = {0, 1}\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Alphabet and Strings implementation.", "Frequently Asked:\n- Define Alphabet and Strings.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Alphabet and Strings."));
            learningResourceRepository.save(createResource(conceptMap.get("Finite Automata basics"), "Finite Automata", "A mathematical model of computation.", "Has states and transitions.", "Accepts or rejects strings.", "The concept of Finite Automata basics is fundamental to mastering Finite Automata. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Finite Automata\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for Finite Automata basics\nHas states and transitions.\n// Usage depends on context", "In real-world applications, Finite Automata basics is used heavily by companies like Google and Meta to optimize their Finite Automata pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply Finite Automata basics principles.\nStep 3: Has states and transitions.\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the Finite Automata basics implementation.", "Frequently Asked:\n- Define Finite Automata basics.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating Finite Automata basics."));
            learningResourceRepository.save(createResource(conceptMap.get("DFA"), "DFA", "Deterministic Finite Automaton.", "For each state and input, exactly one transition.", "No epsilon transitions.", "The concept of DFA is fundamental to mastering Finite Automata. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Finite Automata\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for DFA\nFor each state and input, exactly one transition.\n// Usage depends on context", "In real-world applications, DFA is used heavily by companies like Google and Meta to optimize their Finite Automata pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply DFA principles.\nStep 3: For each state and input, exactly one transition.\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the DFA implementation.", "Frequently Asked:\n- Define DFA.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating DFA."));
            learningResourceRepository.save(createResource(conceptMap.get("CFG"), "CFG", "Rules for generating strings.", "S -> aSb | epsilon", "More powerful than regular expressions.", "The concept of CFG is fundamental to mastering Context-Free Grammars. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Context-Free Grammars\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for CFG\nS -> aSb | epsilon\n// Usage depends on context", "In real-world applications, CFG is used heavily by companies like Google and Meta to optimize their Context-Free Grammars pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply CFG principles.\nStep 3: S -> aSb | epsilon\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the CFG implementation.", "Frequently Asked:\n- Define CFG.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating CFG."));
            learningResourceRepository.save(createResource(conceptMap.get("PDA"), "Pushdown Automata", "Finite Automaton with a stack.", "Accepts context-free languages.", "Stack provides infinite memory.", "The concept of PDA is fundamental to mastering Pushdown Automata. It provides the necessary abstraction and capability to solve complex engineering problems efficiently. Understanding this deeply allows engineers to write better, more scalable, and more reliable systems.", "1. Core element of Pushdown Automata\n2. Critical for performance and readability\n3. Often tested in interviews", "// Standard syntax for PDA\nAccepts context-free languages.\n// Usage depends on context", "In real-world applications, PDA is used heavily by companies like Google and Meta to optimize their Pushdown Automata pipelines and ensure rapid data processing and interface rendering.", "Step 1: Identify requirements.\nStep 2: Apply PDA principles.\nStep 3: Accepts context-free languages.\nResult: System is optimized.", "- Forgetting base cases or initialization.\n- Misunderstanding the lifecycle or scope.\n- Overcomplicating the PDA implementation.", "Frequently Asked:\n- Define PDA.\n- Compare it with alternative approaches.\n- Write a short code snippet demonstrating PDA."));

        };
    }

    private void createQuestionsForConcept(QuestionRepository qr, Concept c, String conceptName, int count) {
        String[] prefixes = {"What is the main purpose of", "Which of the following best describes", "How do you implement", "What is a key characteristic of", "Identify the correct statement about"};
        for(int i=1; i<=count; i++) {
            Question q = new Question();
            q.setConcept(c);
            String prefix = prefixes[i % prefixes.length];
            q.setText(prefix + " " + conceptName + " (Q" + i + ")?");
            q.setOptionA("Correct implementation/definition of " + conceptName);
            q.setOptionB("Incorrect variation 1");
            q.setOptionC("Incorrect variation 2");
            q.setOptionD("Completely unrelated concept");
            q.setCorrectOption("A");
            
            String diff = "MEDIUM";
            if (i <= 3) diff = "EASY";
            else if (i >= 8) diff = "HARD";
            
            q.setDifficultyLevel(diff);
            qr.save(q);
        }
    }

    private LearningResource createResource(Concept c, String title, String exp, String ex, String hint, String detailed, String keyPoints, String syntax, String realWorld, String worked, String mistakes, String exam) {
        LearningResource lr = new LearningResource();
        lr.setConcept(c);
        lr.setTitle(title);
        lr.setShortExplanation(exp);
        lr.setExample(ex);
        lr.setPracticeHint(hint);
        lr.setDetailedExplanation(detailed);
        lr.setKeyPoints(keyPoints);
        lr.setSyntaxOrStructure(syntax);
        lr.setRealWorldExample(realWorld);
        lr.setWorkedExample(worked);
        lr.setCommonMistakes(mistakes);
        lr.setExamPoints(exam);
        return lr;
    }

    private Subject createSubject(String name, String desc) {
        Subject s = new Subject(); s.setName(name); s.setDescription(desc); return s;
    }
    private Chapter createChapter(String name, Subject subject) {
        Chapter c = new Chapter(); c.setName(name); c.setSubject(subject); return c;
    }
    private Concept createConcept(String name, Chapter chapter) {
        Concept c = new Concept(); c.setName(name); c.setChapter(chapter); return c;
    }
}
